### ISSUE TITLE
Something wrong about selecting which convs to be binaried 

### ISSUE THREAD

**Issue by DamonAtSjtu** [gistvision/bnas#1]
In bin_utils_search.py,  line 24-30;
there is something wrong about selecting which convolution kernels to be binaried.
The right way is to choose the 8 * 14 * 4=448 convolutions to be binaried(8 is the number of cells, 14 is the number of lines in a cell, 4 is the options for different convolutions in one line).
However, the code choose the top 448 convolutions to be binaried(including res, prepocess0, preprocess1). The cause is that n here has no effect to distinguish.
I hope your reply!

**Comment by killawhale2** [comment]
Ah, thanks for pointing the typo! 
It must've happened during the refactoring process.
I will push a fix soon.

What the code should be doing is distinguishing certain convolutions to not binarize (such as the preprocess operations) during the **search**. We also tried not distinguishing, but it made little difference to the search result.
The preprocess operations for the final model are binarized (except two downsampling preprocess operations, which is common practice in the literature) with the FLOPs calculated accordingly.
